### ISSUE TITLE
Can you port Crux-with-Icons?

### ISSUE THREAD

**Issue by mscheper** [smurphos/Window_Borders_Mint_19#1]
I was hoping to find a Metacity 3 port of Crux-with-Icons, which is a version of Crux that was modified so it includes window icons. I often cascade my windows, so I find the window icons, at the top left, very helpful. Since you've apparently developed a knack for updating these themes, would you mind including that one? The Metacity 1 version isn't hard to find.

**Comment by mscheper** [comment]
@smurphos: Pls let me know if this is something you'd like to do—I suspect it will be quite a bit easier for you than me. Otherwise, I'll have a go at it, when I have time.

**Comment by smurphos** [comment]
Sorry I missed the notification for your issue. To save me hunting down the Metacity1 version can you post a link? Happy to have a look.

**Comment by smurphos** [comment]
Don't worry found the download. Will take a look over the next few days.

**Comment by smurphos** [comment]
All done - 

https://github.com/smurphos/Window_Borders_Mint_19/commit/02b3414380e1d7a89ac5367ee9088ebf5708cd9d

Updated release download - 

https://github.com/smurphos/Window_Borders_Mint_19/releases/download/v.0.5/metacity_for_mint19_cinn.zip

**Comment by mscheper** [comment]
@smurphos: You're a rockstar for getting on it so quickly.

Unfortunately, I'm still not seeing the icons, on my Cinnamon 3.8.9 system. I just tried again, with the link from README.md: The Crux-with-icons subdirectory is there, and I've copied it, along with all the rest, to ~/.themes, and selected Crux with Icons. It looks the same as plain ol' Crux for me, unfortunately.

I've verified that the ~/.themes/Crux-with-icons/metacity-1/metacity-theme-3.xml file is the same as [in the repo](https://github.com/smurphos/Window_Borders_Mint_19/blob/master/files/Crux-with-icons/metacity-1/metacity-theme-3.xml). I've also made sure that there isn't any Crux-with-icons subdirectory in my /usr/share/themes

Any other ideas for finding out what's wrong?

**Comment by smurphos** [comment]
Check you you've got the menu button enabled in your window manager in the Windows setting module from your menu.

![screenshot-window-2019-01-07-072055](https://user-images.githubusercontent.com/29017677/50754219-d90f8c00-124c-11e9-85d3-9881d496566d.png)

**Comment by mscheper** [comment]
Yep, that was it. Looks great now. Thanks!
