### ISSUE TITLE
Crux Title error  with my config

### ISSUE THREAD

**Issue by laegnur** [smurphos/Window_Borders_Mint_19#10]
Hello
I'm using one of this themes, Crux, and I are having an issue with the title and the middle part of the theme, because I have the window buttons on the left:

![Your image](https://camo.githubusercontent.com/866e8a2af81a7650bd96d13e020d8163409571ab/68747470733a2f2f692e696d6775722e636f6d2f75546f705979582e706e67 "Your image")

![My image](https://i.imgur.com/qIPmiPS.png "My image")

How can I fix that?

**Comment by smurphos** [comment]
Hi,

Apologies for the long delay in reply.

The theme as written is always expecting 3 buttons on the right of the titlebar and no more than one on the left. I don't think there's a way to fix this without creating a variant of the theme for each possible button layout. 

Cinnamon 4.4 offers 2 layouts via GUI (all buttons on left and all on right)

I guess that merits a version of Crux that can accommodate 3 buttons on the left I'll see if I can include it the next time the themes get updated.

**Comment by smurphos** [comment]
Hi, - Crux-Left added by https://github.com/smurphos/Window_Borders_Mint_19/commit/7442e9e95f0e64adc779d3f5a5fd75ade1011ecd

Included in release - https://github.com/smurphos/Window_Borders_Mint_19/releases/tag/v.0.8
