### ISSUE TITLE
Mint-Y-BB Does not display

### ISSUE THREAD

**Issue by ha6000** [smurphos/Window_Borders_Mint_19#11]
I could not locate the Mint-Y-BB themes from Apearance in Linux Mate

**Comment by smurphos** [comment]
Hi, what version of MATE and which Window manager are you using?

**Comment by ha6000** [comment]
**Mate**: 1.22.2
**Window Manager**: Marco + Compositing

**Comment by smurphos** [comment]
Thanks and apologies for the delayed reply. These themes are not intended to support MATE, at at the time of release MATE didn't support metacity version 3 in any case. 

It does now, but for MATE's appearance settings module to pick them up I'll need to add index.theme files. I'll look to do that for the next release.

**Comment by ha6000** [comment]
Thanks a lot

**Comment by smurphos** [comment]
Fixed by https://github.com/smurphos/Window_Borders_Mint_19/commit/ff4f6abd56f6dff243e108d43ff99e6e690af719

In release - https://github.com/smurphos/Window_Borders_Mint_19/releases/tag/v.0.8
