### ISSUE TITLE
Linux Mint 21

### ISSUE THREAD

**Issue by HaagenBl** [smurphos/Window_Borders_Mint_19#12]
Hi,
I used the Mint-Y-Dark VBB in mint 20.3 and loved it. After installing Mint 21 they do no longer pop up in Themes. Are there any plans to update the code to work with mint 21?
Would be absolutely great if there is.
Haagen

**Comment by smurphos** [comment]
Cinnamon 5.4.x doesn't support metacity themes at all so there's no update I can do this end to make these work as in Cinnamon 5.2 and earlier. The window borders are now dependent on the GTK theme in use in Cinnamon 5.4.x.. I will be experimenting at some point when I have some free time with a GTK over-ride for some more control over the WIndow borders but it will be a while.
