### ISSUE TITLE
Problem with the High Contrast theme

### ISSUE THREAD

**Issue by ghost** [smurphos/Window_Borders_Mint_19#2]
Thank you for making (/making available) these themes.

The High Contrast theme was always buggy and indeed with your version the minimize button goes peculiar when hovered over, at least when using a dark control theme.

Screenshot:
![untitled](https://user-images.githubusercontent.com/9998846/47575508-2c568b80-d93a-11e8-9f74-b83020b3fa80.png)

This is a shame, because I really like that theme (especially in the dark mode shown - but I like the Big Buttons version of Mint-Y, too).

EDIT: I find it a bit odd that, in the High Contrast theme, there is a more visible border to a window when the windows in _not_ focused.

**Comment by smurphos** [comment]
@CottonEaster 

Apologies for the delayed response - I unintentionally did not have notifications switched on for this repo.

Issue reproduced - I'll have a look at fixing it.

**Comment by smurphos** [comment]
Fixed by https://github.com/smurphos/Window_Borders_Mint_19/commit/a74aa1a106b98391ea04ccca8ae76a82dc789ada

New release - https://github.com/smurphos/Window_Borders_Mint_19/releases/tag/v.0.6
