### ISSUE TITLE
BB theme doesn't get applied to all windows

### ISSUE THREAD

**Issue by ghost** [smurphos/Window_Borders_Mint_19#5]
Here is an example of a window - the main window of the Disks program - tpo which the theme's borders are not being applied.

![image](https://user-images.githubusercontent.com/9998846/50539645-7991ec00-0b7b-11e9-906b-f15acd0452b2.png)

Mint 19.1 Cinnamon.

**Comment by smurphos** [comment]
Thats because not all windows use a metacity theme. Most gnome apps use a header bar defined by the GTK theme.
