### ISSUE TITLE
High Contrast theme: missing close button on some windows

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [smurphos/Window_Borders_Mint_19#6]
The Nemo options window, as rendered by the High Contrast theme:

![image](https://user-images.githubusercontent.com/47056543/52390988-14db8280-2a93-11e9-9b6a-a44bb6a0f028.png)

Here is the window using a different theme:

![image](https://user-images.githubusercontent.com/47056543/52391029-3c324f80-2a93-11e9-8464-cd2d87726cc9.png)

**Comment by smurphos** [comment]
Thanks for the report - fixed by https://github.com/smurphos/Window_Borders_Mint_19/commit/47b13260f3947251f51de0f56be5345e5b43be33

Updated release - https://github.com/smurphos/Window_Borders_Mint_19/releases/tag/v.0.7
