### ISSUE TITLE
Extraneous red lines on the newest Mint

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [smurphos/Window_Borders_Mint_19#7]
On what is admittedly [an alpha version of Mint Cinnamon](https://github.com/linuxmint/alpha-testing), things go wrong with the BB theme. To wit:

![image](https://user-images.githubusercontent.com/47056543/59552490-8cf51000-8f7f-11e9-87a0-255826ecdbda.png)

Notice the red lines. Those lines disappear when I switch to an inbuilt Mint theme.

**Comment by smurphos** [comment]
Hi,

Apologies for the delayed response. Can you still reproduce this on current alpha / 19.2 beta? I can't reproduce this in the beta on my hardware.

**Comment by LinuxOnTheDesktop** [comment]
I can no longer reproduce, but that may be because I backported (well, er, cut and pasted) code from the newer version of the Mint-Y Dark theme into your BB theme (or rather into a version of your BB theme that I had modified already). I am afraid that I have only a poor record of the changes.
