### ISSUE TITLE
Esco Spacing Breaks in Mint 19.2

### ISSUE THREAD

**Issue by TheDaviot** [smurphos/Window_Borders_Mint_19#9]
It seems the slight update to Cinnamon in 19.2 broke the spacing in the Esco theme, my favorite of the bunch.
Specifically, the window description no long fits inside the title bar meant for it:

[https://i.imgur.com/S1T4jBQ.png](url)

Thanks.

**Comment by smurphos** [comment]
Yeah, I'm aware it's broken in Cinnamon 4.2 - nothing I can do about it.
https://github.com/linuxmint/mint19.2-beta/issues/73

It needs upstream Cinnamon to release a fixed Muffin including this commit

https://github.com/linuxmint/muffin/pull/529
https://github.com/linuxmint/muffin/commit/3c9fdcf6790f65bfc60188b3699de0961f9194b0

Even then a lot of these themes will still be partially broken in that they won't display an application icon when they used to prior to Cinnamon 4.2 / Mint 19.2.

**Comment by TheDaviot** [comment]
I figured you knew; just attempting to be thorough. :)

**Comment by smurphos** [comment]
This issue was resolved by release of Muffin 4.4.0 - https://github.com/linuxmint/muffin/releases/tag/4.4.0
